export const apiKey = [
  "89fa7a5c07874fef8c5c6df66585047e",
  "b98d0bd6b71d4892ac8ddd2c2870e589",
  "f8a353450faf4689b42eda85e220a170",
  "93b9992304aa4b958fa02c65782b932a",
  "438b3b462edd4ec0aa1fcb6988cda8df",
];

export const newsCountry = {
  ar: "Argentina",
  au: "Australia",
  at: "Austria",
  be: "Belgium",
  br: "Brazil",
  bg: "Bulgaria",
  ca: "Canada",
  cn: "China",
  co: "Colombia",
  cu: "Cuba",
  cz: "Czech Republic",
  eg: "Egypt",
  fr: "France",
  de: "Germany",
  gr: "Greece",
  hk: "Hong Kong",
  hu: "Hungary",
  in: "India",
  id: "Indonesia",
  ie: "Ireland",
  il: "Israel",
  it: "Italy",
  jp: "Japan",
  lv: "Latvia",
  lt: "Lithuania",
  my: "Malaysia",
  mx: "Mexico",
  ma: "Morocco",
  nl: "Netherlands",
  nz: "New Zealand",
  ng: "Nigeria",
  no: "Norway",
  ph: "Philippines",
  pl: "Poland",
  pt: "Portugal",
  ro: "Romania",
  ru: "Russia",
  sa: "Saudi Arabia",
  rs: "Serbia",
  sg: "Singapore",
  sk: "Slovakia",
  si: "Slovenia",
  za: "South Africa",
  kr: "South Korea",
  se: "Sweden",
  ch: "Switzerland",
  tw: "Taiwan",
  th: "Thailand",
  tr: "Turkey",
  ae: "UAE",
  ua: "Ukraine",
  gb: "United Kingdom",
  us: "United States",
  ve: "Venuzuela",
};

export const newsCategory = {
  business: "business  ",
  entertainment: "  entertainment  ",
  general: "  general  ",
  health: "  health  ",
  science: "  science  ",
  sports: "  sports  ",
  technology: "  technology  ",
};
